### PR TITLE
LifeCycleAssessment_oM: Update EPD Object Properties

### LINKED ISSUE #791: LifeCycleAssessment_oM: Update EPD property name
#### Description:

Update EnvironmentalProductDeclaration object property from "Masterformat" to "MasterFormat"

### LINKED ISSUE #793: LifeCycleAssessment_oM: Add descriptions
#### Broken rules:
No descriptions on many of the LifeCycleAssessment_oM objects and properties.

#### Suggestions to restore compliance:
Add descriptions.

### LINKED ISSUE #941: LifeCycleAssessment_oM: EPD Adjust Density default value
#### Description:

Adjust Density default value to 0 instead of double.NaN for more effective LCA method error handling within the LCA_Engine.

### LINKED ISSUE #1003: LifeCycleAssessment_oM: EPD Property Updates
#### Description:

Updates to the IEnvironmentalProductDeclaration, EPD and SectorEPD object properties to allow for a greater range of LCA related metrics. Findings are based on additional, more robust datasets that are entering the LCA_Toolkit following these changes.

### LINKED ISSUE #1007: LifeCycleAssessment_oM: Add lifeSpan property to EPD objects

### PR DESCRIPTION
**Pull request by michaelhoehn**
### Issues addressed by this PR

Closes #1003 
Closes #941 
Closes #1007 
Closes #793 
Closes #791 

Additional object properties for more robust data where applicable. 
Default density value set to 0 instead of double.NaN for increased engine method reliability.

### Test files

[Test File ](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/LifeCycleAssessment_Toolkit/LifeCycleAssessment_oM-%231003-EPD-Property-Updates.gh?csf=1&web=1&e=sGb5AT)

### CODE REVIEW

File: LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs [hunk 1]
```diff
@@ -30,33 +31,119 @@ public class EnvironmentalProductDeclaration : BHoMObject, IEnvironmentalProduct
...
-        public virtual string Manufacturer { get; set; } = "";
-        public virtual string Plant { get; set; } = "";
-        public virtual int PostalCode { get; set; } = 0;
-        public virtual List<string> IndustryStandards { get; set; } = new List<string>();
-        public virtual string Id { get; set; } = "";
-        public virtual double Density { get; set; } = double.NaN;
+        [Description("The consequence of acids being emitted to the atmosphere and subsequently deposited in surface soils and waters measured in kg/SO2e.")]
+        public virtual double AcidificationPotential { get; set; } = double.NaN;
+
+        [Description("Amount of the material that comes from a biological source (trees, soil), these materials have the ability sequester/store carbon.")]
```
Comment (FraserGreenroyd) [inline LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs:37]: `these materials have the ability sequester/store carbon` - is that missing a `to` after `ability`?

File: LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs [hunk 2]
```diff
@@ -30,33 +31,119 @@ public class EnvironmentalProductDeclaration : BHoMObject, IEnvironmentalProduct
...
+        [Description("The pollution state of aquatic ecosystems in which the over-fertilization of water and soil has turned into an increased growth of biomass measured in kg/PO4e.")]
+        public virtual double EutrophicationPotential { get; set; } = double.NaN;
+
+        [Description("Exported Electrical Energy or EEE measured in MJ.")]
+        public virtual double ExportedElectricalEnergy { get; set; } = double.NaN;
+
+        [Description("Exported Thermal Energy or EET measured in MJ.")]
+        public virtual double ExportedThermalEnergy { get; set; } = double.NaN;
+
+        [Description("Use of freshwater resources measured in m3.")]
```
Comment (FraserGreenroyd) [inline LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs:64]: Should this be `m^3`?

File: LifeCycleAssessment_oM/MaterialFragment/IEnvironmentalProductDeclarationData.cs [hunk 3]
```diff
@@ -31,26 +33,117 @@ public interface IEnvironmentalProductDeclarationData : IFragment, IMaterialProp
...
+        [Description("The pollution state of aquatic ecosystems in which the over-fertilization of water and soil has turned into an increased growth of biomass measured in kg/PO4e.")]
+        double EutrophicationPotential { get; set; }
+
+        [Description("Exported Electrical Energy or EEE measured in MJ.")]
+        double ExportedElectricalEnergy { get; set; }
+
+        [Description("Exported Thermal Energy or EET measured in MJ.")]
+        double ExportedThermalEnergy { get; set; }
+
+        [Description("Use of freshwater resources measured in m3.")]
```
Comment (FraserGreenroyd) [inline LifeCycleAssessment_oM/MaterialFragment/IEnvironmentalProductDeclarationData.cs:66]: `m^3`?

File: LifeCycleAssessment_oM/MaterialFragment/SectorEnvironmentalProductDeclaration.cs [hunk 4]
```diff
@@ -31,29 +31,125 @@ public class SectorEnvironmentalProductDeclaration : BHoMObject, IEnvironmentalP
...
+        [Description("The pollution state of aquatic ecosystems in which the over-fertilization of water and soil has turned into an increased growth of biomass measured in kg/PO4e.")]
+        public virtual double EutrophicationPotential { get; set; } = double.NaN;
+
+        [Description("Exported Electrical Energy or EEE measured in MJ.")]
+        public virtual double ExportedElectricalEnergy { get; set; } = double.NaN;
+
+        [Description("Exported Thermal Energy or EET measured in MJ.")]
+        public virtual double ExportedThermalEnergy { get; set; } = double.NaN;
+
+        [Description("Use of freshwater resources measured in m3.")]
```
Comment (FraserGreenroyd) [inline LifeCycleAssessment_oM/MaterialFragment/SectorEnvironmentalProductDeclaration.cs:64]: `m^3`?

**Review by FraserGreenroyd — CHANGES_REQUESTED** [review]
Minor description updates - also, can we use any Quantity attributes on any of the properties?

File: LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs [hunk 5]
```diff
@@ -30,33 +31,119 @@ public class EnvironmentalProductDeclaration : BHoMObject, IEnvironmentalProduct
...
         /***************************************************/
-        public virtual QuantityType QuantityType { get; set; } = QuantityType.Undefined;
-        public virtual List<LifeCycleAssessmentPhases> LifeCycleAssessmentPhases { get; set; } = new List<LifeCycleAssessmentPhases>();
-        public virtual string Manufacturer { get; set; } = "";
-        public virtual string Plant { get; set; } = "";
-        public virtual int PostalCode { get; set; } = 0;
-        public virtual List<string> IndustryStandards { get; set; } = new List<string>();
-        public virtual string Id { get; set; } = "";
-        public virtual double Density { get; set; } = double.NaN;
+        [Description("The consequence of acids being emitted to the atmosphere and subsequently deposited in surface soils and waters measured in kg/SO2e.")]
```
Comment (ajensen19) [inline LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs:34]: Acidification, measured in kgSO2e, refers to emissions which increase the H+ ions in the environment causing a decrease in pH. Potential effects include fish mortality, forest decline, and the deterioration of building materials.

File: LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs (hunk 1 above)
Comment (ajensen19) [inline LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs:37]: Biogenic carbon includes emissions, in terms of kgCO2e, related to the natural carbon cycle related to biological-based materials and may involve carbon uptake, fermentation, combustion, etc.

File: LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs [hunk 6]
```diff
@@ -30,33 +31,119 @@ public class EnvironmentalProductDeclaration : BHoMObject, IEnvironmentalProduct
...
+        public virtual double AcidificationPotential { get; set; } = double.NaN;
+
+        [Description("Amount of the material that comes from a biological source (trees, soil), these materials have the ability sequester/store carbon.")]
+        public virtual double BiogenicEmbodiedCarbon { get; set; } = double.NaN;
+
+        [Description("The material density in kg/m^3.")]
+        public virtual double Density { get; set; } = 0;
+
+        [Description("The amount of depletion of non-renewable material resources measured in Sb (Antimony).")]
```
Comment (ajensen19) [inline LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs:45]: Depletion of Abiotic Resources refers to the depletion of nonliving (abiotic) resources such as fossil fuels, minerals, clay, and peat. Units vary.

File: LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs [hunk 7]
```diff
@@ -30,33 +32,121 @@ public class EnvironmentalProductDeclaration : BHoMObject, IEnvironmentalProduct
...
+        public virtual double BiogenicCarbon { get; set; } = double.NaN;
+
+        [Description("The material density in kg/m^3.")]
+        [Density]
+        public virtual double Density { get; set; } = 0;
+
+        [Description("The amount of depletion of non-renewable material resources measured in Sb (Antimony).")]
+        public virtual double DepletionOfAbioticResources { get; set; } = double.NaN;
+
+        [Description("The amount of depletion of non-renewable, fossil fuel material resources measured in kg/MJ.")]
```
Comment (ajensen19) [inline LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs:48]: Depletion of non-renewable Abiotic Resources (fossil fuels) measured in MJ.

Comment (kayleighhoude) [reply LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs:48]: Suggest not using abbreviations: methyl jasmonate (my favorite).

File: LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs [hunk 8]
```diff
@@ -30,33 +32,121 @@ public class EnvironmentalProductDeclaration : BHoMObject, IEnvironmentalProduct
...
+        public virtual double DepletionOfAbioticResourcesFossilFuels { get; set; } = double.NaN;
+
+        [Description("Brief summary of the EPD from the data source.")]
         public virtual string Description { get; set; } = "";
-        public virtual string Scope { get; set; } = "";
+
+        [Description("Description of the material's treatment after its useful life.")]
+        public virtual string EndOfLifeTreatment { get; set; } = "";
+
+        [Description("The pollution state of aquatic ecosystems in which the over-fertilization of water and soil has turned into an increased growth of biomass measured in kg/PO4e.")]
```
Comment (ajensen19) [inline LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs:57]: Eutrophication, measured in kg N equivalents, refers to emissions of nutrients like nitrogen and phosphorus causing overfertilization, leading to overgrowth of biomass that depresses oxygen levels and suffocates ecosystems.

File: LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs [hunk 9]
```diff
@@ -30,33 +32,121 @@ public class EnvironmentalProductDeclaration : BHoMObject, IEnvironmentalProduct
...
+        [Description("Exported Electrical Energy or EEE measured in MJ.")]
+        public virtual double ExportedElectricalEnergy { get; set; } = double.NaN;
+
+        [Description("Exported Thermal Energy or EET measured in MJ.")]
+        public virtual double ExportedThermalEnergy { get; set; } = double.NaN;
+
+        [Description("Use of freshwater resources measured in m^3.")]
+        public virtual double FreshWater { get; set; } = double.NaN;
+
+        [Description("How much heat a greenhouse gas traps in the atmosphere up to a specific time horizon, relative to carbon dioxide measured in kg/CO2e.")]
```
Comment (ajensen19) [inline LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs:69]: Global Warming Potential, expressed in kgCO2e, refers to the emissions of carbon dioxide, methane and other gases that contribute to the greenhouse effect and global warming.

File: LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs [hunk 10]
```diff
@@ -30,33 +32,121 @@ public class EnvironmentalProductDeclaration : BHoMObject, IEnvironmentalProduct
...
+        [Description("Hazardous Waste Disposed or HWD measured in kg.")]
+        public virtual double HazardousWasteDisposed { get; set; } = double.NaN;
+
+        [Description("Unique identifier of the EPD from the source of the information.")]
+        public virtual string Id { get; set; } = "";
+
+        [Description("Industry Standards referenced in creating the product.")]
+        public virtual List<string> IndustryStandards { get; set; } = new List<string>();
+
+        [Description("Phase abreviation for the scope of the EPD. For single phase entries, please input the relevant phase of evaluation i.e. A1 or A1-A3. More information on typical LCA phases can be found in the repository wiki.")]
```
Comment (ajensen19) [inline LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs:81]: Phase "abbreviation" for the scope...(just spelling error)

File: LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs [hunk 11]
```diff
@@ -30,33 +32,121 @@ public class EnvironmentalProductDeclaration : BHoMObject, IEnvironmentalProduct
...
+        public virtual string LifeCycleAssessmentPhase { get; set; } = "Undefined";
+
+        [Description("The period of existence or duration for the product measured in whole years.")]
```
Comment (ajensen19) [inline LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs:84]: The period of useful life of the product measured in years.

File: LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs [hunk 12]
```diff
@@ -30,33 +32,121 @@ public class EnvironmentalProductDeclaration : BHoMObject, IEnvironmentalProduct
...
+        [Description("Material For Energy Recovery or MFR measured in kg.")]
+        public virtual double MaterialForEnergyRecovery { get; set; } = double.NaN;
+
+        [Description("Non-Hazardous Waste Disposed or NHWD measured in kg.")]
+        public virtual double NonHazardousWasteDisposed { get; set; } = double.NaN;
+
+        [Description("Use of Non-renewable Secondary Fuels or NRSF measured in MJ, LHV.")]
+        public virtual double NonRenewableSecondaryFuels { get; set; } = double.NaN;
+
+        [Description("The relative amount of degradation to the ozone layer measured in kg/CFC-11e.")]
```
Comment (ajensen19) [inline LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs:103]: Ozone Depletion Potential, measured in kg CFC-11 equivalents, refers to emissions which contribute to the depletion of the stratospheric ozone layer.

File: LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs [hunk 13]
```diff
@@ -30,33 +32,121 @@ public class EnvironmentalProductDeclaration : BHoMObject, IEnvironmentalProduct
...
         public virtual double OzoneDepletionPotential { get; set; } = double.NaN;
+
+        [Description("The relative abilities of volatile organic compounds (VOCs) to produce ground level ozone (or Ethene) measured in kg/O3e.")]
```
Comment (ajensen19) [inline LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs:106]: Photochemical Ozone Creation Potential, measured in kgO3 equivalents, refers to emissions which contribute to the formation of ground-level smog.

File: LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs [hunk 14]
```diff
@@ -30,33 +32,121 @@ public class EnvironmentalProductDeclaration : BHoMObject, IEnvironmentalProduct
...
+        [Description("Plant within which the product was created.")]
+        public virtual string Plant { get; set; } = "";
+
+        [Description("Postal Code within which the product was created.")]
+        public virtual int PostalCode { get; set; } = 0;
+
+        [Description("Amount of post consumer recycled content measured in kg.")]
         public virtual string PostConsumerRecycledContent { get; set; } = "";
+
+        [Description("Use of non-renewable primary energy excluding raw materials or PENRE measured in MJ, LHV.")]
```
Comment (ajensen19) [inline LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs:118]: Use of non-renewable primary energy excluding raw materials or PENRE measured in MJ.

File: LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs [hunk 15]
```diff
@@ -30,33 +32,121 @@ public class EnvironmentalProductDeclaration : BHoMObject, IEnvironmentalProduct
...
+        public virtual double PrimaryEnergyNonRenewableEnergy { get; set; } = double.NaN;
+
+        [Description("Primary Energy Non-renewable Resources or PENRT is measured in MJ, LHV.")]
```
Comment (ajensen19) [inline LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs:121]: Where is this one coming from?

File: LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs [hunk 16]
```diff
@@ -30,33 +32,121 @@ public class EnvironmentalProductDeclaration : BHoMObject, IEnvironmentalProduct
...
+        public virtual double PrimaryEnergyNonRenewableResource { get; set; } = double.NaN;
+
+        [Description("Primary Energy Renewable-Energy or PERE, is specified in MJ and calculated fro mthe lower calorific value of the energy resources deployed.")]
```
Comment (ajensen19) [inline LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs:124]: Use of renewable energy primary energy in MJ.

File: LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs [hunk 17]
```diff
@@ -30,33 +32,121 @@ public class EnvironmentalProductDeclaration : BHoMObject, IEnvironmentalProduct
...
+        public virtual double PrimaryEnergyRenewableEnergy { get; set; } = double.NaN;
+
+        [Description("Primary Energy Renewable Total or PERT is the total energy resources required to produce a product.")]
```
Comment (ajensen19) [inline LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs:127]: Total use of renewable energy resources required to produce a product, measured in MJ.

File: LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs [hunk 18]
```diff
@@ -30,33 +32,121 @@ public class EnvironmentalProductDeclaration : BHoMObject, IEnvironmentalProduct
...
+        public virtual double PrimaryEnergyRenewableTotal { get; set; } = double.NaN;
+
+        [Description("Primary Energy Resources used as Raw Materials or PERM measured in MJ.")]
```
Comment (ajensen19) [inline LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs:130]: Primary Energy Resources used as raw materials measured in MJ.

File: LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs [hunk 19]
```diff
@@ -30,33 +32,121 @@ public class EnvironmentalProductDeclaration : BHoMObject, IEnvironmentalProduct
...
+        public virtual double PrimaryEnergyResourcesRawMaterials { get; set; } = double.NaN;
+
+        [Description("Radioactive Waste Disposed or RWD measured in kg.")]
```
Comment (ajensen19) [inline LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs:133]: Radioactive Waste Disposed measured in kg.

File: LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs [hunk 20]
```diff
@@ -30,33 +32,121 @@ public class EnvironmentalProductDeclaration : BHoMObject, IEnvironmentalProduct
...
+        public virtual double RadioActiveWasteDisposed { get; set; } = double.NaN;
+
+        [Description("Year in which the EPD was created.")]
         public virtual int ReferenceYear { get; set; } = 0;
+
+        [Description("Use of Renewable Secondary Fuels or RSF measured in MJ, LHV.")]
```
Comment (ajensen19) [inline LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs:139]: Use of Renewable Secondary fuels measured in MJ.

File: LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs [hunk 21]
```diff
@@ -30,33 +32,121 @@ public class EnvironmentalProductDeclaration : BHoMObject, IEnvironmentalProduct
...
+        public virtual double RenewableSecondaryFuels { get; set; } = double.NaN;
+
+        [Description("List the construction scope of the product. Examples include Structures, Foundations, or Enclosures.")]
```
Comment (ajensen19) [inline LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs:142]: this doesn't make any sense to me. a product doesn't have a construction scope. let's omit or where is this coming from? @michaelhoehn

File: LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs [hunk 22]
```diff
@@ -30,33 +32,121 @@ public class EnvironmentalProductDeclaration : BHoMObject, IEnvironmentalProduct
...
+        public virtual string Scope { get; set; } = "";
+
+        [Description("Use of Secondary Material or SM measured in MJ, LHV.")]
```
Comment (ajensen19) [inline LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs:145]: Use of secondary materials measured in kg.

File: LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs [hunk 23]
```diff
@@ -30,33 +32,121 @@ public class EnvironmentalProductDeclaration : BHoMObject, IEnvironmentalProduct
...
+        public virtual double SecondaryMaterial { get; set; } = double.NaN;
+
+        [Description("Key metric for evaluation methods to function. This property determines how the material is to be evaluated, based on Mass, Volume, Area, Item, or Length. Note that any EPD that does not contain this parameter will not be evaluated.")]
```
Comment (ajensen19) [inline LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs:148]: This metric is based on the declared unit of the reference EPD, i.e. a declared unit of kg refers to QuantityType of mass, a declared unit of m3 refers to a QuantityType of volume, etc. All data should be normalized to metric declared units before integration in the BHoM. The quantity type is a key metric for evaluation methods to function. This property determines how the material is to be evaluated, based on Mass, Volume, Area, Item, or Length. Note that any EPD that does not contain this parameter will not be evaluated

File: LifeCycleAssessment_oM/MaterialFragment/IEnvironmentalProductDeclarationData.cs [hunk 24]
```diff
@@ -31,26 +34,119 @@ public interface IEnvironmentalProductDeclarationData : IFragment, IMaterialProp
         /***************************************************/
         /**** Properties                                ****/
         /***************************************************/
-        QuantityType QuantityType { get; set; }
-        List<LifeCycleAssessmentPhases> LifeCycleAssessmentPhases { get; set; }
-        string Id { get; set; }
+        [Description("Acidification, measured in kgSO2e, refers to emissions which increase the H+ ions in the environment causing a decrease in pH. Potential effects include fish mortality, forest decline, and the deterioration of building materials.")]
```
Comment (ajensen19) [inline LifeCycleAssessment_oM/MaterialFragment/IEnvironmentalProductDeclarationData.cs:37]: This looks like a repeat? We need to make all these agree with the definitions noted above as well.

File: LifeCycleAssessment_oM/MaterialFragment/SectorEnvironmentalProductDeclaration.cs [hunk 25]
```diff
@@ -31,29 +32,127 @@ public class SectorEnvironmentalProductDeclaration : BHoMObject, IEnvironmentalP
...
-        public virtual QuantityType QuantityType { get; set; } = QuantityType.Undefined;
-        public virtual List<LifeCycleAssessmentPhases> LifeCycleAssessmentPhases { get; set; }
-        public virtual List<string> Publisher { get; set; } = new List<string>();
-        public virtual List<string> Jurisdiction { get; set; } = new List<string>();
-        public virtual string Id { get; set; } = "";
-        public virtual double Density { get; set; } = double.NaN;
+        [Description("Acidification, measured in kgSO2e, refers to emissions which increase the H+ ions in the environment causing a decrease in pH. Potential effects include fish mortality, forest decline, and the deterioration of building materials.")]
+        public virtual double AcidificationPotential { get; set; } = double.NaN;
+
+        [Description("Biogenic carbon includes emissions, in terms of kgCO2e, related to the natural carbon cycle related to biological-based materials and may involve carbon uptake, fermentation, combustion, etc.")]
```
Comment (ajensen19) [inline LifeCycleAssessment_oM/MaterialFragment/SectorEnvironmentalProductDeclaration.cs:38]: Same agreement is needed here as well with the new definitions.

File: LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs (hunk 15 above)
Comment (michaelhoehn) [reply LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs:121]: @ajensen19 https://www.baubook.info/m/PHP/Fragezeichen.php?S_oekz_Typ=1&SW=16&lng=2

File: LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs (hunk 21 above)
Comment (michaelhoehn) [reply LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs:142]: @ajensen19 this can be used to help the user with a general understanding of the overall product application. It could be removed as I'm not aware of datasets that make use of this property. I'm keen to leave it in for the time being to see if there's any use case for it during this milestone.

File: LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs (hunk 23 above)
Comment (michaelhoehn) [reply LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs:148]: Quite verbose for a typical description, but feel the length is justifiable given the nature of this important property.

File: LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs [hunk 26]
```diff
@@ -30,33 +32,125 @@ public class EnvironmentalProductDeclaration : BHoMObject, IEnvironmentalProduct
...
+        public virtual string Id { get; set; } = "";
+
+        [Description("Industry Standards referenced in creating the product.")]
+        public virtual List<string> IndustryStandards { get; set; } = new List<string>();
+
+        [Description("Phase abbreviation for the scope of the EPD. For single phase entries, please input the relevant phase of evaluation i.e. A1 or A1-A3. More information on typical LCA phases can be found in the repository wiki.")]
+        public virtual string LifeCycleAssessmentPhase { get; set; } = "Undefined";
+
+        [Description("The period of useful life of the product measured in years.")]
+        [Time]
```
Comment (FraserGreenroyd) [inline LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs:85]: The `Time` attribute measures time in seconds, but the description says years. This conflicts.

File: LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs [hunk 27]
```diff
@@ -30,33 +32,125 @@ public class EnvironmentalProductDeclaration : BHoMObject, IEnvironmentalProduct
...
-        public virtual double GlobalWarmingPotentialEndOfLife { get; set; } = double.NaN;
-        public virtual double OzoneDepletionPotentialEndOfLife { get; set; } = double.NaN;
-        public virtual double PhotochemicalOzoneCreationPotentialEndOfLife { get; set; } = double.NaN;
-        public virtual double AcidificationPotentialEndOfLife { get; set; } = double.NaN;
-        public virtual double EutrophicationPotentialEndOfLife { get; set; } = double.NaN;
-        public virtual double DepletionOfAbioticResourcesFossilFuelsEndOfLife { get; set; } = double.NaN;
-        public virtual string EndOfLifeTreatment { get; set; } = "";
-        public virtual string Masterformat { get; set; } = "";
+
+        [Description("Plant within which the product was created.")]
```
Comment (FraserGreenroyd) [inline LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs:109]: What sort of plant? A pot plant? Or industrial plant?

File: LifeCycleAssessment_oM/MaterialFragment/IEnvironmentalProductDeclarationData.cs [hunk 28]
```diff
@@ -31,26 +34,123 @@ public interface IEnvironmentalProductDeclarationData : IFragment, IMaterialProp
...
+        double HazardousWasteDisposed { get; set; }
+
+        [Description("Unique identifier of the EPD from the source of the information.")]
+        string Id { get; set; }
+
+        [Description("Phase abbreviation for the scope of the EPD. For single phase entries, please input the relevant phase of evaluation i.e. A1 or A1-A3. More information on typical LCA phases can be found in the repository wiki.")]
+        string LifeCycleAssessmentPhase { get; set; }
+
+        [Description("The period of useful life of the product measured in years.")]
+        [Time]
```
Comment (FraserGreenroyd) [inline LifeCycleAssessment_oM/MaterialFragment/IEnvironmentalProductDeclarationData.cs:84]: See previous

File: LifeCycleAssessment_oM/MaterialFragment/IEnvironmentalProductDeclarationData.cs [hunk 29]
```diff
@@ -31,26 +34,123 @@ public interface IEnvironmentalProductDeclarationData : IFragment, IMaterialProp
...
-        double DepletionOfAbioticResourcesFossilFuels { get; set; }
-        double GlobalWarmingPotentialEndOfLife { get; set; }
-        double OzoneDepletionPotentialEndOfLife { get; set; }
-        double PhotochemicalOzoneCreationPotentialEndOfLife { get; set; }
-        double AcidificationPotentialEndOfLife { get; set; }
-        double EutrophicationPotentialEndOfLife { get; set; }
-        double DepletionOfAbioticResourcesFossilFuelsEndOfLife { get; set; }
-        string EndOfLifeTreatment { get; set; }
+
+        [Description("Plant within which the product was created.")]
```
Comment (FraserGreenroyd) [inline LifeCycleAssessment_oM/MaterialFragment/IEnvironmentalProductDeclarationData.cs:108]: See previous

File: LifeCycleAssessment_oM/MaterialFragment/SectorEnvironmentalProductDeclaration.cs [hunk 30]
```diff
@@ -31,29 +32,131 @@ public class SectorEnvironmentalProductDeclaration : BHoMObject, IEnvironmentalP
...
+        public virtual List<string> IndustryStandards { get; set; } = new List<string>();
+
+        [Description("Jurisdiction within which the sector based product EPD originates.")]
+        public virtual List<string> Jurisdiction { get; set; } = new List<string>();
+
+        [Description("Phase abbreviation for the scope of the EPD. For single phase entries, please input the relevant phase of evaluation i.e. A1 or A1-A3. More information on typical LCA phases can be found in the repository wiki.")]
+        public virtual string LifeCycleAssessmentPhase { get; set; } = "Undefined";
+
+        [Description("The period of useful life of the product measured in years.")]
+        [Time]
```
Comment (FraserGreenroyd) [inline LifeCycleAssessment_oM/MaterialFragment/SectorEnvironmentalProductDeclaration.cs:88]: See previous

File: LifeCycleAssessment_oM/MaterialFragment/SectorEnvironmentalProductDeclaration.cs [hunk 31]
```diff
@@ -31,29 +32,131 @@ public class SectorEnvironmentalProductDeclaration : BHoMObject, IEnvironmentalP
...
-        public virtual double DepletionOfAbioticResourcesFossilFuels { get; set; } = double.NaN;
-        public virtual double GlobalWarmingPotentialEndOfLife { get; set; } = double.NaN;
-        public virtual double OzoneDepletionPotentialEndOfLife { get; set; } = double.NaN;
-        public virtual double PhotochemicalOzoneCreationPotentialEndOfLife { get; set; } = double.NaN;
-        public virtual double AcidificationPotentialEndOfLife { get; set; } = double.NaN;
-        public virtual double EutrophicationPotentialEndOfLife { get; set; } = double.NaN;
-        public virtual double DepletionOfAbioticResourcesFossilFuelsEndOfLife { get; set; } = double.NaN;
-        public virtual string EndOfLifeTreatment { get; set; } = "";
+
+        [Description("Plant within which the product was created.")]
```
Comment (FraserGreenroyd) [inline LifeCycleAssessment_oM/MaterialFragment/SectorEnvironmentalProductDeclaration.cs:112]: See previous

**Review by FraserGreenroyd — CHANGES_REQUESTED** [review]
Minor things.

Also, can we put the `Quantity` attributes as the first attribute, which matches what we've done on other objects in Environment/MEP/Structure oM :smile:

**Review by ajensen19 — APPROVED** [review]
yay! i finally figured out how to complete a review ;) looks good!

**Comment by michaelhoehn** [comment]
> yay! i finally figured out how to complete a review ;) looks good!

Exciting @ajensen19! Now do it again to cover the changes requested by @FraserGreenroyd 😛

File: LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs [hunk 32]
```diff
@@ -30,33 +32,124 @@ public class EnvironmentalProductDeclaration : BHoMObject, IEnvironmentalProduct
...
+        public virtual double RadioActiveWasteDisposed { get; set; } = double.NaN;
+
+        [Description("Year in which the EPD was created.")]
         public virtual int ReferenceYear { get; set; } = 0;
+
+        [Description("Use of Renewable Secondary fuels measured in megajoules.")]
+        public virtual double RenewableSecondaryFuels { get; set; } = double.NaN;
+
+        [Description("List the construction scope of the product. Examples include Structures, Foundations, or Enclosures.")]
+        public virtual string Scope { get; set; } = "";
```
Comment (michaelhoehn) [inline LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs:142]: Remove Scope property as this is unused and creates ambiguity between other Scope properties used throughout the toolkit. FYI @ajensen19

File: LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs [hunk 33]
```diff
@@ -30,33 +32,124 @@ public class EnvironmentalProductDeclaration : BHoMObject, IEnvironmentalProduct
...
+
+        [Description("Use of secondary materials measured in kg.")]
+        public virtual double SecondaryMaterial { get; set; } = double.NaN;
+
+        [Description("Note that any EPD that does not contain this parameter will not be evaluated." +
+            "This metric is based on the declared unit of the reference EPD, i.e. a declared unit of kg refers to QuantityType of mass, a declared unit of m3 refers to a QuantityType of volume, etc. " +
+            "All data should be normalized to metric declared units before integration in the BHoM. " +
+            "The quantity type is a key metric for evaluation methods to function. " +
+            "This property determines how the material is to be evaluated, based on Mass, Volume, Area, Item, or Length. ")]
+        public virtual QuantityType QuantityType { get; set; } = QuantityType.Undefined;
```
Comment (michaelhoehn) [inline LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs:152]: Add double QuantityTypeValue property to capture material multiplier typically found in EPDs. FYI @ajensen19

**Review by FraserGreenroyd — APPROVED** [review]
LGTM now, thanks @michaelhoehn

**Review by FraserGreenroyd — CHANGES_REQUESTED** [review]
Blocking till dependency PRs are ready

**Review by FraserGreenroyd — APPROVED** [review]
All dependent PRs are done and ready so this LGTM, thanks @michaelhoehn :smile:
